/* Generated by scripts/generate-illustration-dimensions.mjs. */
window.ClassRecordIllustrationDimensions = Object.freeze({
  "resource_1d2bxsu": {
    "width": 395,
    "height": 405
  },
  "resource_0zpeag2": {
    "width": 87,
    "height": 123
  },
  "resource_0gy9jqw": {
    "width": 367,
    "height": 178
  },
  "resource_1oybccs": {
    "width": 1318,
    "height": 1101
  },
  "resource_03dxxjx": {
    "width": 324,
    "height": 365
  },
  "resource_0jfb9ay": {
    "width": 1275,
    "height": 163
  },
  "resource_1ma8sio": {
    "width": 171,
    "height": 156
  },
  "resource_1a6m1h8": {
    "width": 159,
    "height": 120
  },
  "resource_1mia81a": {
    "width": 989,
    "height": 334
  },
  "resource_04t14ux": {
    "width": 258,
    "height": 280
  },
  "resource_09njqoc": {
    "width": 446,
    "height": 867
  },
  "resource_143g5j9": {
    "width": 613,
    "height": 736
  },
  "resource_0r0gros": {
    "width": 2069,
    "height": 1266
  },
  "resource_1vceq7f": {
    "width": 495,
    "height": 856
  },
  "resource_0auz56q": {
    "width": 409,
    "height": 285
  },
  "resource_1t75ap2": {
    "width": 292,
    "height": 304
  },
  "resource_0y6ei8e": {
    "width": 217,
    "height": 152
  },
  "resource_1bzhbov": {
    "width": 182,
    "height": 199
  },
  "resource_1mg7v2t": {
    "width": 3469,
    "height": 507
  },
  "resource_05oh1ro": {
    "width": 594,
    "height": 196
  },
  "resource_1l63vou": {
    "width": 130,
    "height": 137
  },
  "resource_0rlb2e8": {
    "width": 2294,
    "height": 341
  },
  "resource_1ikhgf3": {
    "width": 440,
    "height": 305
  },
  "resource_0m3gnbr": {
    "width": 463,
    "height": 181
  },
  "resource_0ekmt2r": {
    "width": 285,
    "height": 142
  },
  "resource_1snv0fi": {
    "width": 136,
    "height": 134
  },
  "resource_0vfqgop": {
    "width": 366,
    "height": 246
  },
  "resource_0qpo83w": {
    "width": 95,
    "height": 187
  },
  "resource_03blim5": {
    "width": 320,
    "height": 320
  },
  "resource_1g27kew": {
    "width": 249,
    "height": 222
  },
  "resource_05bwomb": {
    "width": 635,
    "height": 878
  },
  "resource_1q2ywjv": {
    "width": 1412,
    "height": 852
  },
  "resource_1ixbu0y": {
    "width": 2167,
    "height": 2382
  },
  "resource_0fa5i4n": {
    "width": 1281,
    "height": 1870
  },
  "resource_15h80mm": {
    "width": 1709,
    "height": 1501
  },
  "resource_1pvg9gd": {
    "width": 1396,
    "height": 850
  },
  "resource_1k7afb3": {
    "width": 2192,
    "height": 3197
  },
  "resource_1efb418": {
    "width": 1876,
    "height": 300
  },
  "resource_1c9w1xj": {
    "width": 2365,
    "height": 3425
  },
  "resource_0tcfdg2": {
    "width": 2856,
    "height": 4284
  },
  "resource_1tznew5": {
    "width": 1623,
    "height": 1129
  },
  "resource_0amsm6k": {
    "width": 2856,
    "height": 4284
  },
  "resource_00rwtt3": {
    "width": 2856,
    "height": 4284
  },
  "resource_17rh2i2": {
    "width": 2856,
    "height": 4284
  },
  "resource_05w9jlp": {
    "width": 2856,
    "height": 4284
  },
  "resource_0jxg9qo": {
    "width": 2856,
    "height": 4284
  },
  "resource_19pmya3": {
    "width": 2856,
    "height": 4284
  },
  "resource_123909a": {
    "width": 2856,
    "height": 4284
  },
  "resource_0aididp": {
    "width": 702,
    "height": 288
  },
  "resource_1q8tqn2": {
    "width": 295,
    "height": 233
  },
  "resource_0a6qi1n": {
    "width": 112,
    "height": 209
  },
  "resource_02a8xss": {
    "width": 263,
    "height": 252
  },
  "resource_02s7ewp": {
    "width": 295,
    "height": 246
  },
  "resource_1snulbu": {
    "width": 263,
    "height": 195
  },
  "resource_0pjjgmv": {
    "width": 270,
    "height": 216
  },
  "resource_01m04uw": {
    "width": 332,
    "height": 230
  },
  "resource_0zu7e1x": {
    "width": 388,
    "height": 279
  },
  "resource_1bknqaz": {
    "width": 919,
    "height": 207
  },
  "resource_1evpcku": {
    "width": 460,
    "height": 234
  },
  "resource_07rabml": {
    "width": 383,
    "height": 300
  },
  "resource_0l3npdc": {
    "width": 306,
    "height": 249
  },
  "resource_1wesjbb": {
    "width": 512,
    "height": 255
  },
  "resource_1wtycei": {
    "width": 424,
    "height": 210
  },
  "resource_1ll57dg": {
    "width": 2856,
    "height": 4284
  },
  "resource_1dl5lan": {
    "width": 2856,
    "height": 4284
  },
  "resource_06nhi5u": {
    "width": 2856,
    "height": 694
  },
  "resource_0ehxxb6": {
    "width": 2856,
    "height": 4284
  },
  "resource_02vaoze": {
    "width": 2856,
    "height": 4284
  },
  "resource_0fczrfp": {
    "width": 1214,
    "height": 1963
  },
  "resource_0v5hhmu": {
    "width": 718,
    "height": 1210
  }
});
