/* Generated by scripts/generate-illustration-dimensions.mjs. */
window.ClassRecordIllustrationDimensions = Object.freeze({
  "data/attachments/02-tag.jpeg": {
    "width": 395,
    "height": 405
  },
  "data/attachments/04-important.jpeg": {
    "width": 87,
    "height": 123
  },
  "data/attachments/04-quote.jpeg": {
    "width": 367,
    "height": 178
  },
  "data/attachments/2024-11-20-01-love.jpeg": {
    "width": 1318,
    "height": 1101
  },
  "data/attachments/2025-03-12-03-tag.jpeg": {
    "width": 324,
    "height": 365
  },
  "data/attachments/2025-08-18-04-password.jpeg": {
    "width": 1275,
    "height": 163
  },
  "data/attachments/2025-09-02-04-qyc.jpeg": {
    "width": 171,
    "height": 156
  },
  "data/attachments/2025-09-03-03-qyc.jpeg": {
    "width": 159,
    "height": 120
  },
  "data/attachments/2025-09-09-01-number-axis.jpeg": {
    "width": 989,
    "height": 334
  },
  "data/attachments/2025-10-14-02-SOCl2.jpeg": {
    "width": 258,
    "height": 280
  },
  "data/attachments/2025-10-23-02-court-death.jpeg": {
    "width": 446,
    "height": 867
  },
  "data/attachments/2025-10-23-02-lock.jpeg": {
    "width": 613,
    "height": 736
  },
  "data/attachments/2025-12-23-03-ban.jpeg": {
    "width": 2069,
    "height": 1266
  },
  "data/attachments/2026-01-24-05-eyes-meet.jpeg": {
    "width": 495,
    "height": 856
  },
  "data/attachments/2026-01-28-01-bond-angle.jpeg": {
    "width": 409,
    "height": 285
  },
  "data/attachments/2026-01-28-01-match.jpeg": {
    "width": 292,
    "height": 304
  },
  "data/attachments/2026-02-02-05-balance.jpeg": {
    "width": 217,
    "height": 152
  },
  "data/attachments/2026-02-11-02-P4.jpeg": {
    "width": 182,
    "height": 199
  },
  "data/attachments/2026-03-07-03-giant.jpeg": {
    "width": 3469,
    "height": 507
  },
  "data/attachments/2026-03-13-01-kong.jpeg": {
    "width": 594,
    "height": 196
  },
  "data/attachments/2026-03-19-03-contrary-pai.jpeg": {
    "width": 130,
    "height": 137
  },
  "data/attachments/2026-03-20-07-password.jpeg": {
    "width": 2294,
    "height": 341
  },
  "data/attachments/2026-03-21-01-little-three.jpeg": {
    "width": 440,
    "height": 305
  },
  "data/attachments/2026-03-26-02-sleep.jpeg": {
    "width": 463,
    "height": 181
  },
  "data/attachments/2026-03-26-02-water-spots.jpeg": {
    "width": 285,
    "height": 142
  },
  "data/attachments/2026-03-26-03-hand.jpeg": {
    "width": 136,
    "height": 134
  },
  "data/attachments/2026-03-31-01-answer.jpeg": {
    "width": 366,
    "height": 246
  },
  "data/attachments/2026-04-15-01-thumb.jpeg": {
    "width": 95,
    "height": 187
  },
  "data/attachments/2026-04-21-01-hihihiha.jpeg": {
    "width": 320,
    "height": 320
  },
  "data/attachments/37-SO.jpeg": {
    "width": 249,
    "height": 222
  },
  "data/attachments/51-qb.jpeg": {
    "width": 635,
    "height": 878
  },
  "data/attachments/985-Pass-Card-origin.jpeg": {
    "width": 1412,
    "height": 852
  },
  "data/attachments/acting-head-teacher-origin.jpeg": {
    "width": 2167,
    "height": 2382
  },
  "data/attachments/acting-head-teacher.jpeg": {
    "width": 1281,
    "height": 1870
  },
  "data/attachments/bobo-origin.jpeg": {
    "width": 1709,
    "height": 1501
  },
  "data/attachments/C9-Pass-Card-origin.jpeg": {
    "width": 1396,
    "height": 850
  },
  "data/attachments/copy-origin.jpeg": {
    "width": 2192,
    "height": 3197
  },
  "data/attachments/god-origin-1.jpeg": {
    "width": 1876,
    "height": 300
  },
  "data/attachments/god-origin-2.jpeg": {
    "width": 2365,
    "height": 3425
  },
  "data/attachments/kyf-origin.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/mystery-origin.jpeg": {
    "width": 1623,
    "height": 1129
  },
  "data/attachments/original-1.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/original-2.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/original-3.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/original-4.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/original-5.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/original-6.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/original-7.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/qin-write-01.jpeg": {
    "width": 702,
    "height": 288
  },
  "data/attachments/qin-write-02.jpeg": {
    "width": 295,
    "height": 233
  },
  "data/attachments/qin-write-03.jpeg": {
    "width": 112,
    "height": 209
  },
  "data/attachments/qin-write-04.jpeg": {
    "width": 263,
    "height": 252
  },
  "data/attachments/qin-write-05.jpeg": {
    "width": 295,
    "height": 246
  },
  "data/attachments/qin-write-06.jpeg": {
    "width": 263,
    "height": 195
  },
  "data/attachments/qin-write-07.jpeg": {
    "width": 270,
    "height": 216
  },
  "data/attachments/qin-write-08.jpeg": {
    "width": 332,
    "height": 230
  },
  "data/attachments/qin-write-09.jpeg": {
    "width": 388,
    "height": 279
  },
  "data/attachments/qin-write-10.jpeg": {
    "width": 919,
    "height": 207
  },
  "data/attachments/qin-write-11.jpeg": {
    "width": 460,
    "height": 234
  },
  "data/attachments/qin-write-12.jpeg": {
    "width": 383,
    "height": 300
  },
  "data/attachments/qin-write-13.jpeg": {
    "width": 306,
    "height": 249
  },
  "data/attachments/qin-write-14.jpeg": {
    "width": 512,
    "height": 255
  },
  "data/attachments/qin-write-15.jpeg": {
    "width": 424,
    "height": 210
  },
  "data/attachments/qin-write-origin-1.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/qin-write-origin-2.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/qin-write-origin-3.jpeg": {
    "width": 2856,
    "height": 694
  },
  "data/attachments/snack-origin.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/thf-origin.jpeg": {
    "width": 2856,
    "height": 4284
  },
  "data/attachments/wang-bo-origin.jpeg": {
    "width": 1214,
    "height": 1963
  },
  "data/attachments/wang-bo.jpeg": {
    "width": 718,
    "height": 1210
  }
});
