-- Migration to the unified site-key gate.
-- Run in Supabase SQL Editor. Replace CHANGE_ME_SITE_KEY before inserting.

create extension if not exists pgcrypto;

create table if not exists public.site_access_keys (
    id bigint generated by default as identity primary key,
    key_hash text not null unique,
    label text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    disabled_at timestamptz
);

alter table public.site_access_keys enable row level security;
revoke all on public.site_access_keys from anon, authenticated;

create or replace function public.verify_site_key(input_key text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
    if input_key is null or length(trim(input_key)) = 0 then
        return false;
    end if;

    return exists (
        select 1
        from public.site_access_keys
        where active = true
          and key_hash = encode(digest(trim(input_key), 'sha256'), 'hex')
    );
end;
$$;

revoke all on function public.verify_site_key(text) from public;
grant execute on function public.verify_site_key(text) to anon, authenticated;

-- Example key insert:
-- insert into public.site_access_keys (key_hash, label)
-- values (encode(digest('CHANGE_ME_SITE_KEY', 'sha256'), 'hex'), 'main key');
