-- Site-key access migration for the no-account frontend.
-- Run in Supabase SQL editor. Replace the sample key before inserting.

create extension if not exists pgcrypto;

create table if not exists public.site_keys (
    id bigint generated by default as identity primary key,
    key_hash text not null,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

alter table public.site_keys enable row level security;

drop policy if exists "site_keys_no_direct_select" on public.site_keys;
create policy "site_keys_no_direct_select"
on public.site_keys for select
to anon, authenticated
using (false);

create or replace function public.verify_site_key(input_key text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
    return exists (
        select 1
        from public.site_keys sk
        where sk.is_active = true
          and sk.key_hash = crypt(input_key, sk.key_hash)
    );
end;
$$;

revoke all on function public.verify_site_key(text) from public;
grant execute on function public.verify_site_key(text) to anon, authenticated;

-- Example: insert the shared site key hash. Replace CHANGE_ME_SITE_KEY first.
-- insert into public.site_keys (key_hash)
-- values (crypt('CHANGE_ME_SITE_KEY', gen_salt('bf', 12)));

-- Records, people, glossary, record pages and quiz questions are read after
-- local key verification. These policies allow the anon client to read data.
alter table public.class_records enable row level security;
alter table public.class_people enable row level security;
alter table public.class_glossary enable row level security;
alter table public.class_record_pages enable row level security;
alter table public.class_quiz_questions enable row level security;

drop policy if exists "class_records_select_anon" on public.class_records;
create policy "class_records_select_anon" on public.class_records for select to anon using (true);

drop policy if exists "class_people_select_anon" on public.class_people;
create policy "class_people_select_anon" on public.class_people for select to anon using (true);

drop policy if exists "class_glossary_select_anon" on public.class_glossary;
create policy "class_glossary_select_anon" on public.class_glossary for select to anon using (true);

drop policy if exists "class_record_pages_select_anon" on public.class_record_pages;
create policy "class_record_pages_select_anon" on public.class_record_pages for select to anon using (true);

drop policy if exists "class_quiz_questions_select_anon" on public.class_quiz_questions;
create policy "class_quiz_questions_select_anon" on public.class_quiz_questions for select to anon using (true);

-- Private bucket signed URL generation still requires object select permission.
drop policy if exists "classrecord_private_read_anon" on storage.objects;
create policy "classrecord_private_read_anon"
on storage.objects for select
to anon
using (bucket_id = 'classrecord-private');

-- Reactions are kept, but are no longer tied to Supabase Auth users.
alter table public.record_reactions add column if not exists actor_key text;
alter table public.record_reactions alter column user_id drop not null;

delete from public.record_reactions
where type = 'favorite';

alter table public.record_reactions drop constraint if exists record_reactions_type_check;
alter table public.record_reactions
    add constraint record_reactions_type_check
    check (type in ('like', 'happy', 'surprised', 'sad', 'angry'));

create unique index if not exists record_reactions_record_actor_type_idx
on public.record_reactions (record_key, actor_key, type)
where actor_key is not null;

alter table public.record_reactions enable row level security;

drop policy if exists "reactions_select_authenticated" on public.record_reactions;
drop policy if exists "reactions_insert_self" on public.record_reactions;
drop policy if exists "reactions_delete_self" on public.record_reactions;
drop policy if exists "reactions_select_anon" on public.record_reactions;
drop policy if exists "reactions_insert_anon" on public.record_reactions;
drop policy if exists "reactions_delete_anon" on public.record_reactions;

create policy "reactions_select_anon"
on public.record_reactions for select
to anon
using (type in ('like', 'happy', 'surprised', 'sad', 'angry'));

create policy "reactions_insert_anon"
on public.record_reactions for insert
to anon
with check (
    actor_key is not null
    and length(actor_key) between 8 and 120
    and type in ('like', 'happy', 'surprised', 'sad', 'angry')
);

create policy "reactions_delete_anon"
on public.record_reactions for delete
to anon
using (actor_key is not null);

-- Optional: remove frontend dependency on comments. Keep tables if you want
-- historical data, but make sure old Auth-only policies no longer affect the app.
drop policy if exists "comments_select_authenticated" on public.record_comments;
drop policy if exists "comments_insert_self" on public.record_comments;
drop policy if exists "comments_update_self" on public.record_comments;
drop policy if exists "comments_delete_self" on public.record_comments;

-- Review queues are optional. The updated frontend submits actor_key instead
-- of user_id; make old user_id columns nullable if these forms should work.
alter table public.correction_requests add column if not exists actor_key text;
alter table public.wall_messages add column if not exists actor_key text;
alter table public.person_claim_requests add column if not exists actor_key text;
alter table public.person_edit_requests add column if not exists actor_key text;

alter table public.correction_requests alter column user_id drop not null;
alter table public.wall_messages alter column user_id drop not null;
alter table public.person_claim_requests alter column user_id drop not null;
alter table public.person_edit_requests alter column user_id drop not null;

drop policy if exists "correction_insert_own" on public.correction_requests;
create policy "correction_insert_anon"
on public.correction_requests for insert
to anon
with check (actor_key is not null);

drop policy if exists "wall_select_approved_own_or_admin" on public.wall_messages;
create policy "wall_select_approved_anon"
on public.wall_messages for select
to anon
using (status = 'approved');

drop policy if exists "wall_insert_own" on public.wall_messages;
create policy "wall_insert_anon"
on public.wall_messages for insert
to anon
with check (actor_key is not null);

-- Optional cleanup for the old recursive profiles admin policy. The new
-- frontend no longer queries profiles, but this prevents direct old paths from
-- hitting a recursive role policy.
drop function if exists public.is_admin();
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select false;
$$;
