-- Safe migration for:
-- - class_glossary / term naming -> class_quotes / quote naming
-- - written page supplements
-- - materials
--
-- Run after backing up the project. This script preserves old columns when
-- they already exist, but all frontend reads should use the new quote fields.

do $$
begin
    if to_regclass('public.class_quotes') is null
       and to_regclass('public.class_glossary') is not null then
        alter table public.class_glossary rename to class_quotes;
    end if;
end $$;

create table if not exists public.class_quotes (
    id text primary key,
    quote_id text,
    quote text,
    aliases jsonb not null default '[]'::jsonb,
    content text,
    source_date text,
    related_people jsonb not null default '[]'::jsonb,
    record_file text,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

alter table public.class_quotes add column if not exists quote_id text;
alter table public.class_quotes add column if not exists quote text;
alter table public.class_quotes add column if not exists aliases jsonb not null default '[]'::jsonb;
alter table public.class_quotes add column if not exists content text;
alter table public.class_quotes add column if not exists source_date text;
alter table public.class_quotes add column if not exists related_people jsonb not null default '[]'::jsonb;
alter table public.class_quotes add column if not exists record_file text;
alter table public.class_quotes add column if not exists sort_order integer;
alter table public.class_quotes add column if not exists raw jsonb not null default '{}'::jsonb;

do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'class_quotes' and column_name = 'term_id'
    ) then
        update public.class_quotes
        set quote_id = coalesce(quote_id, term_id);
    end if;

    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'class_quotes' and column_name = 'term'
    ) then
        update public.class_quotes
        set quote = coalesce(quote, term);
    end if;

    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'class_quotes' and column_name = 'definition'
    ) then
        update public.class_quotes
        set content = coalesce(content, definition);
    end if;

    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'class_quotes' and column_name = 'since'
    ) then
        update public.class_quotes
        set source_date = coalesce(source_date, since);
    end if;
end $$;

update public.class_quotes
set quote_id = coalesce(quote_id, id),
    quote = coalesce(quote, raw->>'quote', raw->>'term', id),
    content = coalesce(content, raw->>'content', raw->>'definition', ''),
    source_date = coalesce(source_date, raw->>'sourceDate', raw->>'since');

alter table public.class_quotes enable row level security;

drop policy if exists "class_glossary_read" on public.class_quotes;
drop policy if exists "class_quotes_read" on public.class_quotes;
create policy "class_quotes_read"
on public.class_quotes for select
to anon, authenticated
using (true);

create table if not exists public.class_page_supplements (
    id bigint generated by default as identity primary key,
    file_name text not null unique,
    page text not null,
    supplement_index integer not null,
    author text,
    content text not null,
    hidden boolean not null default false,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

create index if not exists class_page_supplements_page_idx
on public.class_page_supplements (hidden, page, supplement_index);

alter table public.class_page_supplements enable row level security;
drop policy if exists "class_page_supplements_read" on public.class_page_supplements;
create policy "class_page_supplements_read"
on public.class_page_supplements for select
to anon, authenticated
using (true);

create table if not exists public.class_materials (
    id text primary key,
    material_id text,
    title text not null,
    content text not null,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

alter table public.class_materials enable row level security;
drop policy if exists "class_materials_read" on public.class_materials;
create policy "class_materials_read"
on public.class_materials for select
to anon, authenticated
using (true);

notify pgrst, 'reload schema';
