-- Add written page supplements and materials tables to an existing Supabase project.
-- 名言不再有独立表；前端会从普通记录正文的 [[quote:id|内容]] 标记中派生名言列表。

create table if not exists public.class_page_supplements (
    id bigint generated by default as identity primary key,
    file_name text not null unique,
    page text not null,
    supplement_index integer not null,
    author text,
    content text not null,
    hidden boolean not null default false,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

create index if not exists class_page_supplements_page_idx
on public.class_page_supplements (hidden, page, supplement_index);

alter table public.class_page_supplements enable row level security;

drop policy if exists "class_page_supplements_read" on public.class_page_supplements;
create policy "class_page_supplements_read"
on public.class_page_supplements for select
to anon, authenticated
using (true);

create table if not exists public.class_materials (
    id text primary key,
    material_id text,
    title text not null,
    content text not null,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

alter table public.class_materials enable row level security;

drop policy if exists "class_materials_read" on public.class_materials;
create policy "class_materials_read"
on public.class_materials for select
to anon, authenticated
using (true);

notify pgrst, 'reload schema';
