-- Class archive Supabase setup.
-- Execute this file in Supabase SQL Editor first.
--
-- This script creates:
-- 1. site key hash table
-- 2. verify_site_key(input_key text) RPC
-- 3. read-only content tables used by the frontend, including page messages
-- 4. RLS policies for necessary read access
-- 5. Storage signed URL support for the private bucket
--
-- It does not insert a real site key. After this file succeeds, run
-- docs/supabase-key-operations.sql to add your key.

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- ---------------------------------------------------------------------------
-- Unified site key
-- ---------------------------------------------------------------------------

create table if not exists public.site_access_keys (
    id bigint generated by default as identity primary key,
    key_hash text not null unique,
    label text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    disabled_at timestamptz
);

alter table public.site_access_keys enable row level security;
revoke all on public.site_access_keys from anon, authenticated;

create or replace function public.verify_site_key(input_key text)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
begin
    if input_key is null or length(trim(input_key)) = 0 then
        return false;
    end if;

    return exists (
        select 1
        from public.site_access_keys
        where active = true
          and key_hash = encode(extensions.digest(convert_to(trim(input_key), 'UTF8'), 'sha256'), 'hex')
    );
end;
$$;

revoke all on function public.verify_site_key(text) from public;
grant execute on function public.verify_site_key(text) to anon, authenticated;

-- ---------------------------------------------------------------------------
-- Content tables read by the frontend
-- ---------------------------------------------------------------------------

create table if not exists public.class_records (
    id bigint generated by default as identity primary key,
    file_name text not null unique,
    record_id text,
    record_index integer,
    record_date text,
    record_time text,
    author text,
    content text,
    importance text,
    hidden boolean not null default false,
    attachments jsonb not null default '[]'::jsonb,
    image_path text,
    raw jsonb not null default '{}'::jsonb
);

create table if not exists public.class_people (
    id text primary key,
    person_id text,
    name text,
    aliases jsonb not null default '[]'::jsonb,
    alias text,
    role text,
    subject text,
    bio text,
    avatar_url text,
    raw jsonb not null default '{}'::jsonb
);

-- Keep existing installations compatible when this setup script is rerun.
alter table public.class_people
add column if not exists subject text;

create table if not exists public.class_glossary (
    id text primary key,
    term_id text,
    term text,
    aliases jsonb not null default '[]'::jsonb,
    definition text,
    since text,
    related_people jsonb not null default '[]'::jsonb,
    raw jsonb not null default '{}'::jsonb
);

create table if not exists public.class_record_pages (
    id bigint generated by default as identity primary key,
    page text not null unique,
    start_file text,
    end_file text,
    image_path text,
    hidden boolean not null default false,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

create table if not exists public.class_page_messages (
    id bigint generated by default as identity primary key,
    page text not null unique,
    content text not null,
    author text,
    raw jsonb not null default '{}'::jsonb
);

create table if not exists public.class_quiz_questions (
    id text primary key,
    content_key text,
    question_group text,
    question_type text,
    prompt text,
    choices jsonb not null default '[]'::jsonb,
    answer text,
    explanation text,
    image_path text,
    sort_order integer,
    raw jsonb not null default '{}'::jsonb
);

alter table public.class_records enable row level security;
alter table public.class_people enable row level security;
alter table public.class_glossary enable row level security;
alter table public.class_record_pages enable row level security;
alter table public.class_page_messages enable row level security;
alter table public.class_quiz_questions enable row level security;

drop policy if exists "class_records_read" on public.class_records;
create policy "class_records_read"
on public.class_records for select
to anon, authenticated
using (true);

drop policy if exists "class_people_read" on public.class_people;
create policy "class_people_read"
on public.class_people for select
to anon, authenticated
using (true);

drop policy if exists "class_glossary_read" on public.class_glossary;
create policy "class_glossary_read"
on public.class_glossary for select
to anon, authenticated
using (true);

drop policy if exists "class_record_pages_read" on public.class_record_pages;
create policy "class_record_pages_read"
on public.class_record_pages for select
to anon, authenticated
using (true);

drop policy if exists "class_page_messages_read" on public.class_page_messages;
create policy "class_page_messages_read"
on public.class_page_messages for select
to anon, authenticated
using (true);

drop policy if exists "class_quiz_questions_read" on public.class_quiz_questions;
create policy "class_quiz_questions_read"
on public.class_quiz_questions for select
to anon, authenticated
using (true);

-- ---------------------------------------------------------------------------
-- Storage signed URL support
-- ---------------------------------------------------------------------------

insert into storage.buckets (id, name, public)
values ('classrecord-private', 'classrecord-private', false)
on conflict (id) do update
set public = false;

drop policy if exists "classrecord_private_read" on storage.objects;
create policy "classrecord_private_read"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'classrecord-private');

-- Refresh Supabase PostgREST schema cache so /rpc/verify_site_key appears.
notify pgrst, 'reload schema';
